
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: argocd-2-gitops
  description: Contains the ArgoCD manifests for argocd-2
  annotations:
    argocd/app-name: argocd-2-gitops
    backstage.io/kubernetes-id: argocd-2-gitops
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: BlackMamba97s/argocd-2-gitops
spec:
  type: gitops
  system: argocd
  lifecycle: production
  owner: default:default/guest
  dependsOn:
    - component:default/argocd
